import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import HomeIcon from "@/assets/icons/HomeIcon";
import AddIcon from "@/assets/icons/AddIcon";
import SandGlassIcon from "@/assets/icons/SandGlassIcon";
import CorrectIcon from "@/assets/icons/CorrectIcon";
import CrossIcon from "@/assets/icons/CrossIcon";
import StopIcon from "@/assets/icons/StopIcon";
import SideButton from "@/components/button/SideButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="pt-32 absolute w-80 transition-all left-0 top-0 bottom-0 flex flex-col">
          <div className="flex-1">
            <SideButton>
              <HomeIcon style="w-10" />
              <span className="flex-1 text-left pl-5">Tasks</span>
              <AddIcon style="w-10" />
            </SideButton>
            <SideButton>
              <SandGlassIcon style="w-10" />
              <span className="flex-1 text-left pl-5">In progress</span>
            </SideButton>
            <SideButton>
              <CorrectIcon style="w-10" />
              <span className="flex-1 text-left pl-5">Checked</span>
            </SideButton>
            <SideButton>
              <CrossIcon style="w-10" />
              <span className="flex-1 text-left pl-5">Not Checked</span>
            </SideButton>
          </div>
          <div className="h-20">
            <SideButton>
              <StopIcon style="w-10" />
              <span className="flex-1 text-left pl-5">Log out</span>
            </SideButton>
          </div>
        </div>
        <div className="absolute inset-0 left-80 transition-all">
          <div className="flex justify-end items-end w-full pr-10 h-16">
            <span className="text-gray-700">Welcome,</span>
            <span className="text-blue-600 cursor-pointer">
              Nichapat Thitithanakorn
            </span>
          </div>
          <div className="p-10">{children}</div>
        </div>
      </body>
    </html>
  );
}
